-- migrate:up
CREATE TABLE users(
  id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  banner VARCHAR(255),
  about_me JSONB,
  experience BIGINT NOT NULL DEFAULT 0,
  main_color VARCHAR(255),
  links JSONB DEFAULT '[]'::jsonb,
  facts JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE friends(
  id VARCHAR(255) PRIMARY KEY,
  sender_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  accepted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);


CREATE TABLE servers(
  id VARCHAR(255) PRIMARY KEY,
  owner_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  banner VARCHAR(255),
  description JSONB,
  public BOOLEAN NOT NULL DEFAULT FALSE,
  main_color VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE channel_categories(
  id VARCHAR(255) PRIMARY KEY,
  position INT NOT NULL DEFAULT 0,
  server_id VARCHAR(255) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  users VARCHAR(255) ARRAY,
  roles VARCHAR(255) ARRAY,
  e2ee BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE channels(
  id VARCHAR(255) PRIMARY KEY,
  position INT NOT NULL DEFAULT 0,
  server_id VARCHAR(255) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  category_id VARCHAR(255) NOT NULL REFERENCES channel_categories(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  type VARCHAR(255) NOT NULL,
  users VARCHAR(255) ARRAY,
  roles VARCHAR(255) ARRAY,
  e2ee BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE channel_pins(
  id VARCHAR(255) PRIMARY KEY,
  position INT NOT NULL DEFAULT 0,
  server_id VARCHAR(255) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  channel_id VARCHAR(255) NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE roles(
  id VARCHAR(255) PRIMARY KEY,
  server_id VARCHAR(255) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  position INT NOT NULL DEFAULT 0,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL,
  abilities VARCHAR(255) ARRAY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE messages(
  id VARCHAR(255) PRIMARY KEY,
  author_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  server_id VARCHAR(255) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  channel_id VARCHAR(255) NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  content JSONB NOT NULL,
  everyone BOOLEAN NOT NULL DEFAULT FALSE,
  mentions_users VARCHAR(255) ARRAY,
  mentions_roles VARCHAR(255) ARRAY,
  mentions_channels VARCHAR(255) ARRAY,
  attachments JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE server_members(
  id VARCHAR(255) PRIMARY KEY,
  position INT NOT NULL DEFAULT 0,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  server_id VARCHAR(255) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  roles VARCHAR(255) ARRAY,
  nickname varchar(255),
  ban BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(user_id, server_id)
);

CREATE TABLE invites(
  id VARCHAR(255) PRIMARY KEY,
  creator_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  server_id VARCHAR(255) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  invite_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  expire_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE emojis(
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  shortcode VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  expire_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE user_channel_read_state(
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_id VARCHAR(255) NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  last_read_message_id VARCHAR(255) REFERENCES messages(id) ON DELETE CASCADE,
  unread_mention_ids JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (user_id, channel_id)
);

CREATE TABLE tokens(
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  type VARCHAR(255) NOT NULL,
  expire_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_tokens_token ON tokens(token);
CREATE INDEX idx_invites_invite_id ON invites(invite_id);

-- dumb user to create the global server
INSERT INTO users
VALUES ('global', 'admin', 'admin', '', '');

-- dumb server to create dm channels for friends
INSERT INTO servers
VALUES ('global', 'global', 'global');

-- migrate:down
DROP TABLE emojis;
DROP TABLE user_channel_read_state;
DROP TABLE invites;
DROP TABLE tokens;
DROP TABLE server_members;
DROP TABLE messages;
DROP TABLE roles;
DROP TABLE channel_pins;
DROP TABLE channels;
DROP TABLE channel_categories;
DROP TABLE servers;
DROP TABLE friends;
DROP TABLE users;
